import React, { useState, useEffect, useRef } from 'react';
import { IconInfo, IconRefresh } from '../constants';

const UpdateNotifier: React.FC = () => {
    const [newVersionAvailable, setNewVersionAvailable] = useState(false);
    const [isChecking, setIsChecking] = useState(false);
    const initialScriptSrc = useRef<string | null>(null);

    const getMainScriptSrc = () => {
        const scripts = Array.from(document.scripts);
        // This targets the main script generated by Vite's build process.
        const mainScript = scripts.find(s => s.type === 'module' && s.src.includes('/assets/index-'));
        return mainScript?.src || null;
    };
    
    const checkForUpdates = async () => {
        // Don't check if we are already checking, or if we couldn't find the initial script
        if (isChecking || !initialScriptSrc.current) {
            return;
        }

        setIsChecking(true);
        try {
            // Fetch the root HTML file with a cache-busting query parameter
            const response = await fetch(`/?t=${Date.now()}`);
            const html = await response.text();
            
            // Extract the new script's relative path using a regex
            const match = html.match(/<script type="module" src="(\/assets\/index-[^"]+\.js)"><\/script>/);
            
            if (match && match[1]) {
                const newScriptSrc = new URL(match[1], window.location.origin).href;
                
                // If the new src is different from the initial one, a new version is available
                if (newScriptSrc !== initialScriptSrc.current) {
                    console.log('New version detected!', { old: initialScriptSrc.current, new: newScriptSrc });
                    setNewVersionAvailable(true);
                }
            }
        } catch (error) {
            console.error('Failed to check for new version:', error);
        } finally {
            setIsChecking(false);
        }
    };

    useEffect(() => {
        // Set the initial script source on mount
        initialScriptSrc.current = getMainScriptSrc();
        if (!initialScriptSrc.current) {
            console.warn('UpdateNotifier: Could not find initial script. Version checking will be disabled.');
            return;
        }

        // Check for updates every 15 minutes
        const interval = setInterval(checkForUpdates, 15 * 60 * 1000);

        // Also check when the tab becomes visible again
        const handleVisibilityChange = () => {
            if (document.visibilityState === 'visible') {
                checkForUpdates();
            }
        };

        document.addEventListener('visibilitychange', handleVisibilityChange);

        return () => {
            clearInterval(interval);
            document.removeEventListener('visibilitychange', handleVisibilityChange);
        };
    }, []);

    const handleRefresh = () => {
        window.location.reload();
    };

    const handleDismiss = () => {
        setNewVersionAvailable(false);
    };

    if (!newVersionAvailable) {
        return null;
    }

    return (
        <div role="alert" aria-live="assertive" className="fixed bottom-6 right-6 z-[100] bg-slate-800 text-white rounded-lg shadow-2xl p-4 w-full max-w-sm border border-slate-700">
            <div className="flex items-start gap-3">
                <div className="shrink-0 pt-1">
                    <IconInfo className="w-5 h-5 text-slate-400" />
                </div>
                <div>
                    <h3 className="font-semibold text-slate-100">A new version is available</h3>
                    <p className="text-sm text-slate-300 mt-1">Refresh to see the latest changes.</p>
                </div>
            </div>
            <div className="flex justify-end gap-3 mt-4">
                <button
                    onClick={handleDismiss}
                    className="px-4 py-1.5 text-sm font-medium rounded-md bg-slate-600/50 text-slate-200 hover:bg-slate-600"
                >
                    Not now
                </button>
                <button
                    onClick={handleRefresh}
                    className="flex items-center gap-2 px-4 py-1.5 text-sm font-medium rounded-md bg-green-600 hover:bg-green-700"
                >
                    <IconRefresh className="w-4 h-4" />
                    Refresh
                </button>
            </div>
        </div>
    );
};

export default UpdateNotifier;